# Generated by Django 5.0.7 on 2024-08-19 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_version"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="version",
            options={
                "ordering": ["product_name", "number_version", "name_version"],
                "verbose_name": "Версия",
                "verbose_name_plural": "Версии",
            },
        ),
        migrations.RemoveField(
            model_name="version",
            name="product",
        ),
        migrations.AddField(
            model_name="version",
            name="product_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="version",
                to="catalog.product",
                verbose_name="Версия продукта",
            ),
        ),
    ]
