# Generated by Django 4.2.2 on 2024-08-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_product_creator"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["category", "name"],
                "permissions": [
                    ("can_edit_description", "Can edit description"),
                    ("can_edit_category", "Can edit category"),
                    ("can_edit_is_publication", "Can edit is publication"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_publication",
            field=models.BooleanField(default=True, verbose_name="Опубликовать?"),
        ),
    ]
