# Generated by Django 4.2.2 on 2024-08-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_product_options_product_is_publication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_publication",
            field=models.BooleanField(default=False, verbose_name="Опубликовать?"),
        ),
    ]
